### ISSUE TITLE
Explore more redirects to members.html

### ISSUE THREAD

**Issue by nirmalya8** [S4DS-IEM/s4ds-iem-website#5]
@Shayan990 
The `Explore more` button under our works on the main page does not redirect to the page you made. It redirects to `/members.html ` .See if you can fix this. I am creating an issue in the repo for this bug.

**Comment by Shayan990** [comment]
But for me it is redirecting to the projects.html I made.

**Comment by nirmalya8** [comment]
> But for me it is redirecting to the projects.html I made.

Check in the main website. https://s4ds-iem.github.io/s4ds-iem-website/

**Comment by nirmalya8** [comment]
It's coming now @Shayan990 . Thanks.
