### ISSUE TITLE
Centre Buttons

### ISSUE THREAD

**Issue by chaitak-gorai** [S4DS-IEM/s4ds-iem-website#8]
Centre the explore more buttons of all three sections- About us, Recent works, Members.

**Comment by Avila5301** [comment]
Hi, I would like to take this issue.

**Comment by techsouvik** [comment]
go on @Avila5301

**Comment by chaitak-gorai** [comment]
This is issue is solved by the commits  18431220208b8e9a35961f04a9d6bae9209ce6b9 and 066eef3870b3f57f2395ec2ef4d2171874e403dc.

Special thanks to @Avila5301 for this contribution.
